name: 'Auto-Assign Reviewers and Label to New PR'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews-and-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "PR: Needs Review"